### ISSUE TITLE
How to specify ssl port.

### ISSUE THREAD

**Issue by thetechnaddict** [hellstad/meteor-please#2]
The deployment server does not use port 22 for ssh...

adding the following to the servers section (if 2222 were the correct port) solves the issue.

"sshOptions": { "port" : 2222 }

**Comment by kevincharm** [comment]
Sorry, haven't had a chance to test out with SSL... Thanks for this, will make it clearer :-)

**Comment by thetechnaddict** [comment]
I am so very sorry - The comment was about ssh!  [I've edited the title to correct]

**Comment by kevincharm** [comment]
haha, okay. I got confused myself. I'll update the readme - thank you!
